## defaults for _all_ profiles
[default]
address = "127.0.0.1"
port = 19119
limits = { form = "128MiB", json = "128MiB", data = "128MiB", data-form = "128MiB", bytes = "128MiB", file = "128MiB"}

[default.shutdown]
ctrlc = true
signals = ["term", "hup"]
grace = 5
mercy = 2